spring:
  application:
    name: resto
  datasource:
    url: jdbc:mysql://localhost:3306/resto_db?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  servlet:
    context-path: /app/${spring.application.name}